In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("6M-0K-99K.users.dataset.public.csv")

In [4]:
df.head()

,identifierHash,type,country,language,socialNbFollowers,socialNbFollows,socialProductsLiked,productsListed,productsSold,productsPassRate,...,civilityTitle,hasAnyApp,hasAndroidApp,hasIosApp,hasProfilePicture,daysSinceLastLogin,seniority,seniorityAsMonths,seniorityAsYears,countryCode
0,-7279641312655250028,user,Etats-Unis,en,3,8,0,0,0,0.0,...,mrs,False,False,False,True,709,3205,106.83,8.9,us
1,-1456013578740053406,user,Allemagne,de,3,8,0,0,0,0.0,...,mrs,False,False,False,True,709,3205,106.83,8.9,de
2,9006282053848196165,user,Suède,en,3,8,0,0,0,0.0,...,mr,True,False,True,True,689,3205,106.83,8.9,se
3,-7154634866120535654,user,Turquie,en,3,8,0,0,0,0.0,...,mrs,False,False,False,True,709,3205,106.83,8.9,tr
4,2858299215060733023,user,France,en,3,8,0,0,0,0.0,...,mr,True,False,True,True,709,3205,106.83,8.9,fr

In [5]:
df.count()

identifierHash         98913
type                   98913
country                98913
language               98913
socialNbFollowers      98913
socialNbFollows        98913
socialProductsLiked    98913
productsListed         98913
productsSold           98913
productsPassRate       98913
productsWished         98913
productsBought         98913
gender                 98913
civilityGenderId       98913
civilityTitle          98913
hasAnyApp              98913
hasAndroidApp          98913
hasIosApp              98913
hasProfilePicture      98913
daysSinceLastLogin     98913
seniority              98913
seniorityAsMonths      98913
seniorityAsYears       98913
countryCode            98913
dtype: int64

In [7]:
# Calculate the size of each chunk
chunk_size = len(df) // 5 + (1 if len(df) % 5 else 0)

# Split the dataframe into chunks and save them
for i in range(5):
    start = i * chunk_size
    end = start + chunk_size
    chunk_df = df.iloc[start:end]
    chunk_df.to_csv(f'chunk-data/chunk{i+1}.csv', index=False)

In [8]:
df=pd.read_csv("users.6M0xxK.2024.public.csv")

In [9]:
# Calculate the size of each chunk
chunk_size = len(df) // 5 + (1 if len(df) % 5 else 0)

# Split the dataframe into chunks and save them
for i in range(5):
    start = i * chunk_size
    end = start + chunk_size
    chunk_df = df.iloc[start:end]
    chunk_df.to_csv(f'chunk-data/chunk{i+5+1}.csv', index=False)